[general]
import = [
    "~/.config/alacritty/themes/themes/catppuccin_frappe.toml"
]
  [font]
size = 10.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[window.padding]
x = 6
y = 4

[terminal.shell]
program = "/usr/bin/fish"
