wallpaper {
    monitor = LVDS-1
    path = ~/Pictures/wall.png
    fit_mode = cover 
  }
wallpaper {
    monitor = HDMI-A-1 
    path = ~/Pictures/wall.png
    fit_mode = cover
  }

splash = false
#wallpaper = ,~/Pictures/wallpaper/wall.png
