general {
    gaps_in = 2 
    gaps_out = 4 

    border_size = 1 
    
    col.inactive_border = rgba(107,65,47,1)
    col.active_border = rgba(153,177,181,1)

    layout = dwindle
}

  decoration {

    rounding = 2
    rounding_power = 2   
  
    active_opacity = 0.99 
    inactive_opacity = 0.9 

    blur {
        enabled = true
        size = 8 
        passes = 3

        vibrancy = 0.1696
    }
}

