# Float, center and animate Alacritty
windowrule {
  name = move-Alacritty
  match:class = Alacritty

  float = on
  center = on
  animation = popin
  size = 700 500
}
windowrule {
  name = nemo-float
  match:class = nemo

  float = on
  center = on
  animation = popin
  size = 700 400
}
windowrule {
    name = btop-float
    match:class = Alacritty
    match:title = btop

    size = 750 700
  }

windowrule {
    name = wifitui-float
    match:class = Alacritty
    match:title = wifitui

    size = 600 500
  }



windowrule = match:class Alacritty, rounding 10
windowrule = match:class (pinentry-)(.*), stay_focused on

#windowrule = hyprbars:no_bar on, match:class ^(Alacritty)$

