#Base of bindings
$Terminal = alacritty
$menu = rofi -show drun
$file = nautilus
$browser = firefox

#W key bindings
bindd = SUPER, W, Close window, killactive,
bind = SUPER SHIFT, W, exec, poweroff
bind = SUPER ALT, W, exec, reboot

#Assign bind
bindd = SUPER, RETURN, Terminal, exec, $Terminal
bindd = SUPER, E, FileManager, exec, $file
bindd = SUPER, SPACE, Applauncher, exec, $menu
bindd = SUPER, B, browser, exec, $browser 
bindd = SUPER, M, Music, exec, spotify-launcher
bindd = SUPER, Y, Music, exec, chromium --app=https://www.youtube.com
bindd = SUPER, V, Code, exec, code
bindd = SUPER, O, Obsidian, exec, obsidian -disable-gpu

#task Manager
bind = SUPER,Q,exec,alacritty -T btop -e btop
bind = SUPER,C,exec,alacritty -T wiremix -e wiremix
bind = SUPER SHIFT, B, exec, alacritty -T bluetui -e bluetui
bind = SUPER, N, exec, alacritty -T wifitui -e wifitui

#move windows focus
bindd = SUPER, H, Move window focus left, movefocus, l
bindd = SUPER, L, Move window focus right, movefocus, r 
bindd = SUPER, J, Move window focus up, movefocus, u 
bindd = SUPER, K, Move window focus down, movefocus, d 

#move windows focus with arrow key
bindd = SUPER, left, Move window focus left, movefocus, l
bindd = SUPER, right, Move window focus right, movefocus, r 
bindd = SUPER, up, Move window focus up, movefocus, u
bindd = SUPER, down, Move window focus down, movefocus, d 

#waybar custom
bind = SUPER SHIFT, SPACE, exec, pkill -SIGUSR1 waybar

#brightnessontrol
bind = SUPER, A, exec, brightnessctl set +10%
bind = SUPER SHIFT, A, exec, brightnessctl set 10%-

#toggle hdmi 
bind = SUPER_SHIFT, H, exec, ~/.config/hypr/scripts/toggle_hdmi.sh

#assign for screenshot
bind = SUPER, S, exec, hyprshot -m window
bind = SUPER_SHIFT, S, exec, hyprshot -m output
bind = SUPER_CTRL, S, exec, hyprshot -m region | wl-copy,

bind = , XF86AudioRaiseVolume, exec, media-control volume_up
bind = , XF86AudioLowerVolume, exec, media-control volume_down
bind = , XF86AudioMute, exec, media-control volume_mute

bind = , XF86MonBrightnessUp, exec, media-control brightness_up
bind = , XF86MonBrightnessDown, exec, media-control brightness_down
