
#Sources of files
source = ~/.config/hypr/bind.conf
source = ~/.config/hypr/tiling.conf
source = ~/.config/hypr/looks.conf
source = ~/.config/hypr/monitor.conf
source = ~/.config/hypr/envs.conf
source = ~/.config/hypr/window.conf
source = ~/.config/hypr/plugins.conf
#Run app
exec-once = waybar
exec-once = hyprpaper
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once = hyprpm reload -n
exec-once = swaync

misc {
    disable_hyprland_logo = true
    force_default_wallpaper = -1
}
