general {
    lock_cmd = pidof hyprlock || hyprlock       # avoid starting multiple hyprlock instances.
    before_sleep_cmd = loginctl lock-session    # lock before suspend.
    after_sleep_cmd = hyprctl dispatch dpms on 
    ignore_dbus_inhibit = true                   # to avoid having to press a key twice to turn on the display.
}

# 1. DIM DISPLAY (After 2.5 mins)
listener {
    timeout = 150                                
    on-timeout = brightnessctl -s set 10         # set monitor backlight to 10%
    on-resume = brightnessctl -r                 # restore monitor backlight
}

# 2. LOCK SCREEN (After 5 mins)
listener {
    timeout = 300                                
    on-timeout = loginctl lock-session           # lock screen
}

# 3. TURN OFF SCREEN (After 5.5 mins)
listener {
    timeout = 330                                
    on-timeout = hyprctl dispatch dpms off       # screen off
    on-resume = hyprctl dispatch dpms on         # screen on when activity detected
}

# 4. SUSPEND/SHUTDOWN (Optional - After 30 mins)
listener {
    timeout = 1800                                
    on-timeout = systemctl suspend                # suspend pc
}

