plugin {
    hyprbars {
        bar_height = 23
        bar_color = rgba(30, 30, 30, 0.8) # Dark glass look
        col.text = rgb(ffffff)
        bar_text_size = 12
        bar_text_font = "JetBrainsMono Nerd Font" # Recommended macOS font
        bar_precedence_over_border = true
        bar_buttons_alignment = left
        bar_color = rgb(1e1e2e)
        buttons_pad = 10

        # Syntax: bgcolor, size, icon, on-click, [fgcolor]
        hyprbars-button = rgb(ff5f56), 12, , hyprctl dispatch killactive
        hyprbars-button = rgb(ffbd2e), 12, , hyprctl dispatch togglefloating
        hyprbars-button = rgb(27c93f), 12, , hyprctl dispatch fullscreen 1
    }
}

